<?php

declare(strict_types=1);

namespace Cobblestone\World\Internal;

use Cobblestone\World\BlockType;
use Cobblestone\World\Light\BlockLightProperties;

/** @internal Exact asset vocabulary and recovered static light metadata for BlockType. */
final class BlockTypeMetadata
{
    private function __construct()
    {
    }

    public static function assetName(BlockType $type): string
    {
        return match ($type) {
            BlockType::Air => 'air',
            BlockType::Stone => 'stone',
            BlockType::Grass => 'grass',
            BlockType::Dirt => 'dirt',
            BlockType::Cobblestone => 'cobblestone',
            BlockType::Planks => 'planks',
            BlockType::Sapling => 'sapling',
            BlockType::Bedrock => 'bedrock',
            BlockType::FlowingWater => 'flowing_water',
            BlockType::Water => 'water',
            BlockType::FlowingLava => 'flowing_lava',
            BlockType::Lava => 'lava',
            BlockType::Sand => 'sand',
            BlockType::Gravel => 'gravel',
            BlockType::GoldOre => 'gold_ore',
            BlockType::IronOre => 'iron_ore',
            BlockType::CoalOre => 'coal_ore',
            BlockType::Log => 'log',
            BlockType::Leaves => 'leaves',
            BlockType::SpongeDry => 'sponge.dry',
            BlockType::Glass => 'glass',
            BlockType::LapisOre => 'lapis_ore',
            BlockType::LapisBlock => 'lapis_block',
            BlockType::Dispenser => 'dispenser',
            BlockType::Sandstone => 'sandstone',
            BlockType::NoteBlock => 'noteblock',
            BlockType::Bed => 'bed',
            BlockType::GoldenRail => 'golden_rail',
            BlockType::DetectorRail => 'detector_rail',
            BlockType::StickyPiston => 'sticky_piston',
            BlockType::Web => 'web',
            BlockType::TallGrass => 'tallgrass',
            BlockType::DeadBush => 'deadbush',
            BlockType::Piston => 'piston',
            BlockType::PistonArmCollision => 'pistonArmCollision',
            BlockType::Wool => 'wool',
            BlockType::YellowFlower => 'yellow_flower',
            BlockType::RedFlower => 'red_flower',
            BlockType::BrownMushroom => 'brown_mushroom',
            BlockType::RedMushroom => 'red_mushroom',
            BlockType::GoldBlock => 'gold_block',
            BlockType::IronBlock => 'iron_block',
            BlockType::DoubleStoneSlab => 'double_stone_slab',
            BlockType::StoneSlab => 'stone_slab',
            BlockType::BrickBlock => 'brick_block',
            BlockType::Tnt => 'tnt',
            BlockType::Bookshelf => 'bookshelf',
            BlockType::MossyCobblestone => 'mossy_cobblestone',
            BlockType::Obsidian => 'obsidian',
            BlockType::Torch => 'torch',
            BlockType::Fire => 'fire',
            BlockType::MobSpawner => 'mob_spawner',
            BlockType::OakStairs => 'oak_stairs',
            BlockType::Chest => 'chest',
            BlockType::RedstoneWire => 'redstone_wire',
            BlockType::DiamondOre => 'diamond_ore',
            BlockType::DiamondBlock => 'diamond_block',
            BlockType::CraftingTable => 'crafting_table',
            BlockType::Wheat => 'wheat',
            BlockType::Farmland => 'farmland',
            BlockType::Furnace => 'furnace',
            BlockType::LitFurnace => 'lit_furnace',
            BlockType::StandingSign => 'standing_sign',
            BlockType::WoodenDoor => 'wooden_door',
            BlockType::Ladder => 'ladder',
            BlockType::Rail => 'rail',
            BlockType::StoneStairs => 'stone_stairs',
            BlockType::WallSign => 'wall_sign',
            BlockType::Lever => 'lever',
            BlockType::StonePressurePlate => 'stone_pressure_plate',
            BlockType::IronDoor => 'iron_door',
            BlockType::WoodenPressurePlate => 'wooden_pressure_plate',
            BlockType::RedstoneOre => 'redstone_ore',
            BlockType::LitRedstoneOre => 'lit_redstone_ore',
            BlockType::UnlitRedstoneTorch => 'unlit_redstone_torch',
            BlockType::RedstoneTorch => 'redstone_torch',
            BlockType::StoneButton => 'stone_button',
            BlockType::SnowLayer => 'snow_layer',
            BlockType::Ice => 'ice',
            BlockType::Snow => 'snow',
            BlockType::Cactus => 'cactus',
            BlockType::Clay => 'clay',
            BlockType::Reeds => 'reeds',
            BlockType::Fence => 'fence',
            BlockType::Pumpkin => 'pumpkin',
            BlockType::Netherrack => 'netherrack',
            BlockType::SoulSand => 'soul_sand',
            BlockType::Glowstone => 'glowstone',
            BlockType::Portal => 'portal',
            BlockType::LitPumpkin => 'lit_pumpkin',
            BlockType::Cake => 'cake',
            BlockType::UnpoweredRepeater => 'unpowered_repeater',
            BlockType::PoweredRepeater => 'powered_repeater',
            BlockType::InvisibleBedrock => 'invisibleBedrock',
            BlockType::Trapdoor => 'trapdoor',
            BlockType::MonsterEgg => 'monster_egg',
            BlockType::StoneBrick => 'stonebrick',
            BlockType::BrownMushroomBlock => 'brown_mushroom_block',
            BlockType::RedMushroomBlock => 'red_mushroom_block',
            BlockType::IronBars => 'iron_bars',
            BlockType::GlassPane => 'glass_pane',
            BlockType::MelonBlock => 'melon_block',
            BlockType::PumpkinStem => 'pumpkin_stem',
            BlockType::MelonStem => 'melon_stem',
            BlockType::Vine => 'vine',
            BlockType::FenceGate => 'fence_gate',
            BlockType::BrickStairs => 'brick_stairs',
            BlockType::StoneBrickStairs => 'stone_brick_stairs',
            BlockType::Mycelium => 'mycelium',
            BlockType::WaterLily => 'waterlily',
            BlockType::NetherBrick => 'nether_brick',
            BlockType::NetherBrickFence => 'nether_brick_fence',
            BlockType::NetherBrickStairs => 'nether_brick_stairs',
            BlockType::NetherWart => 'nether_wart',
            BlockType::EnchantingTable => 'enchanting_table',
            BlockType::BrewingStand => 'brewing_stand',
            BlockType::Cauldron => 'cauldron',
            BlockType::EndPortalFrame => 'end_portal_frame',
            BlockType::EndStone => 'end_stone',
            BlockType::RedstoneLamp => 'redstone_lamp',
            BlockType::LitRedstoneLamp => 'lit_redstone_lamp',
            BlockType::Dropper => 'dropper',
            BlockType::ActivatorRail => 'activator_rail',
            BlockType::Cocoa => 'cocoa',
            BlockType::SandstoneStairs => 'sandstone_stairs',
            BlockType::EmeraldOre => 'emerald_ore',
            BlockType::TripwireHook => 'tripwire_hook',
            BlockType::TripWire => 'tripWire',
            BlockType::EmeraldBlock => 'emerald_block',
            BlockType::SpruceStairs => 'spruce_stairs',
            BlockType::BirchStairs => 'birch_stairs',
            BlockType::JungleStairs => 'jungle_stairs',
            BlockType::CobblestoneWall => 'cobblestone_wall',
            BlockType::FlowerPot => 'flower_pot',
            BlockType::Carrots => 'carrots',
            BlockType::Potatoes => 'potatoes',
            BlockType::WoodenButton => 'wooden_button',
            BlockType::Skull => 'skull',
            BlockType::Anvil => 'anvil',
            BlockType::TrappedChest => 'trapped_chest',
            BlockType::LightWeightedPressurePlate => 'light_weighted_pressure_plate',
            BlockType::HeavyWeightedPressurePlate => 'heavy_weighted_pressure_plate',
            BlockType::UnpoweredComparator => 'unpowered_comparator',
            BlockType::PoweredComparator => 'powered_comparator',
            BlockType::DaylightDetector => 'daylight_detector',
            BlockType::RedstoneBlock => 'redstone_block',
            BlockType::QuartzOre => 'quartz_ore',
            BlockType::Hopper => 'hopper',
            BlockType::QuartzBlock => 'quartz_block',
            BlockType::QuartzStairs => 'quartz_stairs',
            BlockType::DoubleWoodenSlab => 'double_wooden_slab',
            BlockType::WoodenSlab => 'wooden_slab',
            BlockType::StainedHardenedClay => 'stained_hardened_clay',
            BlockType::Leaves2 => 'leaves2',
            BlockType::Log2 => 'log2',
            BlockType::AcaciaStairs => 'acacia_stairs',
            BlockType::DarkOakStairs => 'dark_oak_stairs',
            BlockType::Slime => 'slime',
            BlockType::IronTrapdoor => 'iron_trapdoor',
            BlockType::HayBlock => 'hay_block',
            BlockType::Carpet => 'carpet',
            BlockType::HardenedClay => 'hardened_clay',
            BlockType::CoalBlock => 'coal_block',
            BlockType::PackedIce => 'packed_ice',
            BlockType::DoublePlant => 'double_plant',
            BlockType::DaylightDetectorInverted => 'daylight_detector_inverted',
            BlockType::RedSandstone => 'red_sandstone',
            BlockType::RedSandstoneStairs => 'red_sandstone_stairs',
            BlockType::DoubleStoneSlab2 => 'double_stone_slab2',
            BlockType::StoneSlab2 => 'stone_slab2',
            BlockType::SpruceFenceGate => 'spruce_fence_gate',
            BlockType::BirchFenceGate => 'birch_fence_gate',
            BlockType::JungleFenceGate => 'jungle_fence_gate',
            BlockType::DarkOakFenceGate => 'dark_oak_fence_gate',
            BlockType::AcaciaFenceGate => 'acacia_fence_gate',
            BlockType::SpruceDoor => 'spruce_door',
            BlockType::BirchDoor => 'birch_door',
            BlockType::JungleDoor => 'jungle_door',
            BlockType::AcaciaDoor => 'acacia_door',
            BlockType::DarkOakDoor => 'dark_oak_door',
            BlockType::GrassPath => 'grass_path',
            BlockType::Frame => 'frame',
            BlockType::Podzol => 'podzol',
            BlockType::Beetroot => 'beetroot',
            BlockType::Stonecutter => 'stonecutter',
            BlockType::GlowingObsidian => 'glowingobsidian',
            BlockType::NetherReactor => 'netherreactor',
            BlockType::InfoUpdate => 'info_update',
            BlockType::InfoUpdate2 => 'info_update2',
            BlockType::MovingBlock => 'movingBlock',
            BlockType::Reserved6 => 'reserved6',
        };
    }

    public static function lightProperties(BlockType $type): BlockLightProperties
    {
        /** @var array<int, BlockLightProperties> $cache */
        static $cache = [];

        return $cache[$type->value] ??= new BlockLightProperties(
            self::lightBlock($type),
            self::lightEmission($type),
        );
    }

    private static function lightBlock(BlockType $type): int
    {
        return match ($type) {
            BlockType::Stone,
            BlockType::Grass,
            BlockType::Dirt,
            BlockType::Cobblestone,
            BlockType::Planks,
            BlockType::Bedrock,
            BlockType::Sand,
            BlockType::Gravel,
            BlockType::GoldOre,
            BlockType::IronOre,
            BlockType::CoalOre,
            BlockType::Log,
            BlockType::SpongeDry,
            BlockType::LapisOre,
            BlockType::LapisBlock,
            BlockType::Dispenser,
            BlockType::Sandstone,
            BlockType::NoteBlock,
            BlockType::StickyPiston,
            BlockType::Piston,
            BlockType::PistonArmCollision,
            BlockType::Wool,
            BlockType::GoldBlock,
            BlockType::IronBlock,
            BlockType::DoubleStoneSlab,
            BlockType::BrickBlock,
            BlockType::Tnt,
            BlockType::Bookshelf,
            BlockType::MossyCobblestone,
            BlockType::Obsidian,
            BlockType::MobSpawner,
            BlockType::DiamondOre,
            BlockType::DiamondBlock,
            BlockType::CraftingTable,
            BlockType::Furnace,
            BlockType::LitFurnace,
            BlockType::RedstoneOre,
            BlockType::LitRedstoneOre,
            BlockType::Snow,
            BlockType::Clay,
            BlockType::Pumpkin,
            BlockType::Netherrack,
            BlockType::SoulSand,
            BlockType::Glowstone,
            BlockType::LitPumpkin,
            BlockType::MonsterEgg,
            BlockType::StoneBrick,
            BlockType::BrownMushroomBlock,
            BlockType::RedMushroomBlock,
            BlockType::MelonBlock,
            BlockType::Mycelium,
            BlockType::NetherBrick,
            BlockType::EndStone,
            BlockType::RedstoneLamp,
            BlockType::LitRedstoneLamp,
            BlockType::Dropper,
            BlockType::EmeraldOre,
            BlockType::EmeraldBlock,
            BlockType::RedstoneBlock,
            BlockType::QuartzOre,
            BlockType::QuartzBlock,
            BlockType::DoubleWoodenSlab,
            BlockType::StainedHardenedClay,
            BlockType::Log2,
            BlockType::Slime,
            BlockType::HayBlock,
            BlockType::HardenedClay,
            BlockType::CoalBlock,
            BlockType::PackedIce,
            BlockType::RedSandstone,
            BlockType::DoubleStoneSlab2,
            BlockType::Podzol,
            BlockType::Stonecutter,
            BlockType::GlowingObsidian,
            BlockType::NetherReactor,
            BlockType::InfoUpdate,
            BlockType::InfoUpdate2,
            BlockType::Reserved6
                => 15,
            default => 0,
        };
    }

    private static function lightEmission(BlockType $type): int
    {
        return match ($type) {
            BlockType::FlowingLava,
            BlockType::Lava,
            BlockType::Fire,
            BlockType::Glowstone,
            BlockType::LitPumpkin,
            BlockType::LitRedstoneLamp => 15,
            BlockType::Torch => 14,
            BlockType::LitFurnace,
            BlockType::GlowingObsidian => 13,
            BlockType::Portal => 11,
            BlockType::LitRedstoneOre => 9,
            BlockType::RedstoneTorch,
            BlockType::PoweredRepeater,
            BlockType::PoweredComparator => 7,
            BlockType::BrownMushroom => 1,
            default => 0,
        };
    }
}
