[package]
name = "cobblestone-world"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bench]]
name = "world"
harness = false

[dependencies]
cobblestone-runtime = { path = "../runtime" }

[lints.rust]
unsafe_code = "forbid"
