<?php

declare(strict_types=1);

namespace Cobblestone\World;

// @generated by `cargo xtask generate` from `spec/`. DO NOT EDIT.

use ValueError;

final readonly class BiomeId
{
    public const OCEAN = 0;
    public const PLAINS = 1;
    public const DESERT = 2;
    public const EXTREME_HILLS = 3;
    public const FOREST = 4;
    public const TAIGA = 5;
    public const SWAMPLAND = 6;
    public const RIVER = 7;
    public const HELL = 8;
    public const FROZEN_OCEAN = 10;
    public const FROZEN_RIVER = 11;
    public const ICE_PLAINS = 12;
    public const ICE_MOUNTAINS = 13;
    public const MUSHROOM_ISLAND = 14;
    public const MUSHROOM_ISLAND_SHORE = 15;
    public const BEACH = 16;
    public const DESERT_HILLS = 17;
    public const FOREST_HILLS = 18;
    public const TAIGA_HILLS = 19;
    public const EXTREME_HILLS_EDGE = 20;
    public const JUNGLE = 21;
    public const JUNGLE_HILLS = 22;
    public const JUNGLE_EDGE = 23;
    public const DEEP_OCEAN = 24;
    public const STONE_BEACH = 25;
    public const COLD_BEACH = 26;
    public const BIRCH_FOREST = 27;
    public const BIRCH_FOREST_HILLS = 28;
    public const ROOFED_FOREST = 29;
    public const COLD_TAIGA = 30;
    public const COLD_TAIGA_HILLS = 31;
    public const MEGA_TAIGA = 32;
    public const MEGA_TAIGA_HILLS = 33;
    public const EXTREME_HILLS_PLUS = 34;
    public const SAVANNA = 35;
    public const SAVANNA_PLATEAU = 36;
    public const MESA = 37;
    public const MESA_PLATEAU_F = 38;
    public const MESA_PLATEAU = 39;
    public const SUNFLOWER_PLAINS = 129;
    public const DESERT_M = 130;
    public const EXTREME_HILLS_M = 131;
    public const FLOWER_FOREST = 132;
    public const TAIGA_M = 133;
    public const SWAMPLAND_M = 134;
    public const ICE_PLAINS_SPIKES = 140;
    public const JUNGLE_M = 149;
    public const JUNGLE_EDGE_M = 151;
    public const BIRCH_FOREST_M = 155;
    public const BIRCH_FOREST_HILLS_M = 156;
    public const ROOFED_FOREST_M = 157;
    public const COLD_TAIGA_M = 158;
    public const MEGA_SPRUCE_TAIGA = 160;
    public const REDWOOD_TAIGA_HILLS_M = 161;
    public const EXTREME_HILLS_PLUS_M = 162;
    public const SAVANNA_M = 163;
    public const SAVANNA_PLATEAU_M = 164;
    public const MESA_BRYCE = 165;
    public const MESA_PLATEAU_F_M = 166;
    public const MESA_PLATEAU_M = 167;

    public function __construct(public int $value)
    {
        if (!BiomeCatalog::supports($value)) {
            throw new ValueError("unsupported MCPE 0.15.10 biome id {$value}");
        }
    }

    public function name(): string
    {
        return BiomeCatalog::name($this->value);
    }

    public function defaultColor(): int
    {
        return BiomeCatalog::defaultColor($this->value);
    }

    public function column(): BiomeColumn
    {
        return BiomeColumn::forId($this);
    }
}
