<?php

declare(strict_types=1);

namespace Cobblestone\Internal;

// @generated by `cargo xtask generate` from `spec/`. DO NOT EDIT.

final class Target
{
    public const GAME_VERSION = "0.15.10";
    public const GAME_PROTOCOL = 84;
    public const RAKNET_PROTOCOL = 8;

    private function __construct() {}
}
