use crate::population::{PopulationNeighborhood, state};

const AIR: u16 = 0;
const FLOWING_WATER: u16 = 8;
const STILL_WATER: u16 = 9;
const ICE: u16 = 79;

const RAIN_HEIGHT_MAX: i32 = 127;

/// Exact Minecraft: Windows 10 Edition Beta 0.15.10 freezeFrostProcess stage.
///
/// Despite the target profile name, this pass does not place top-snow. The 0.15.10 executable
/// scans the center chunk's 16x16 columns after Monster Rooms and freezes source-level water in
/// cold biomes. It runs before biome decoration and before the final light/height update.
///
/// The executable also checks block light < 10. Generated center chunks still have zero block-light
/// nibbles at this boundary; earlier emitters are only deferred until the later lighting pass.
/// PopulationNeighborhood intentionally models that generation boundary rather than arbitrary
/// already-lit runtime chunks.
#[derive(Debug, Default, Copy, Clone)]
pub struct OverworldFreezeFrostPopulator;

impl OverworldFreezeFrostPopulator {
    pub const fn new() -> Self {
        Self
    }

    pub fn populate(&self, neighborhood: &mut PopulationNeighborhood) {
        let center = neighborhood.center();
        let origin_x = center.x().wrapping_mul(16);
        let origin_z = center.z().wrapping_mul(16);

        for offset_x in 0..16_i32 {
            for offset_z in 0..16_i32 {
                let x = origin_x.wrapping_add(offset_x);
                let z = origin_z.wrapping_add(offset_z);
                let y = top_rain_y(neighborhood, x, z).wrapping_sub(1);

                if !biome_freezes(neighborhood.biome_id(x, z).unwrap_or(1)) {
                    continue;
                }
                if !(0..=RAIN_HEIGHT_MAX).contains(&y) {
                    continue;
                }

                let Some(current) = neighborhood.state(x, y, z) else {
                    continue;
                };
                let id = current >> 4;
                let data = (current & 0x0f) as u8;
                if matches!(id, FLOWING_WATER | STILL_WATER) && data == 0 {
                    let _ = neighborhood.set_state(x, y, z, state(ICE, 0));
                }
            }
        }
    }
}

/// Fixed-target LevelChunk::getTopRainBlockPos over generated population state.
///
/// The Win10 0.15.10 binary starts at y=127, never examines y=0, and caps a discovered y+1 back
/// to 127. That makes y=126 and y=127 share the same returned rain height.
fn top_rain_y(neighborhood: &PopulationNeighborhood, x: i32, z: i32) -> i32 {
    let mut y = RAIN_HEIGHT_MAX;
    while y > 0 {
        if material_blocks_motion_or_is_liquid(neighborhood.block_id(x, y, z)) {
            return y.wrapping_add(1).min(RAIN_HEIGHT_MAX);
        }
        y -= 1;
    }
    -1
}

/// Material::getBlocksMotion() || Material::isLiquid() for IDs reachable before this stage.
///
/// Water/lava count as rain blockers even though they do not block motion. The listed exceptions
/// are the gas/decoration/plant/portal materials generated by terrain, structures, and dungeons
/// before freeze/frost. This is deliberately a generation-stage domain, not a general block API.
const fn material_blocks_motion_or_is_liquid(id: u16) -> bool {
    !matches!(
        id,
        AIR | 30
            | 50
            | 55
            | 59
            | 65
            | 66
            | 69
            | 93
            | 106
            | 119
            | 131
            | 132
            | 140
            | 141
            | 142
            | 143
            | 244
    )
}

/// Target biomes whose fixed temperature is <= Biome::RAIN_TEMP_THRESHOLD (0.15f).
///
/// Pocket Edition does not apply the Java high-altitude temperature adjustment here. Mutated
/// biomes inherit their contained biome temperature.
const fn biome_freezes(id: u8) -> bool {
    matches!(id, 10 | 11 | 12 | 13 | 26 | 30 | 31 | 140 | 158)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ChunkCoord;

    const STONE: u16 = 1;
    const TORCH: u16 = 50;

    fn hash_neighborhood(neighborhood: &PopulationNeighborhood) -> u64 {
        neighborhood
            .state_planes()
            .flat_map(|states| states.iter())
            .fold(0xcbf2_9ce4_8422_2325_u64, |mut hash, value| {
                for byte in value.to_le_bytes() {
                    hash = (hash ^ u64::from(byte)).wrapping_mul(0x100_0000_01b3);
                }
                hash
            })
    }

    fn block_count(neighborhood: &PopulationNeighborhood, id: u16) -> usize {
        neighborhood
            .state_planes()
            .flat_map(|states| states.iter())
            .filter(|value| (**value >> 4) == id)
            .count()
    }

    #[test]
    fn independent_mixed_negative_coordinate_fixture_matches() {
        // Standalone C++ block-array oracle reproducing the 0.15.10 executable's rain-height
        // scan, cold-biome threshold, zero pre-light block-light plane, water metadata gate, and
        // ice write. The fixture intentionally includes decorations above water and the y=127 cap.
        let center = ChunkCoord::new(-1, -1);
        let mut neighborhood = PopulationNeighborhood::filled(center, state(AIR, 0), 12);
        let origin_x = -16;
        let origin_z = -16;

        for x in 0..16_i32 {
            for z in 0..16_i32 {
                let world_x = origin_x + x;
                let world_z = origin_z + z;
                let _ = neighborhood.set_state(world_x, 60, world_z, state(STONE, 0));
                match (x + z) & 3 {
                    0 => {
                        let _ = neighborhood.set_state(world_x, 61, world_z, state(STILL_WATER, 0));
                    }
                    1 => {
                        let _ =
                            neighborhood.set_state(world_x, 61, world_z, state(FLOWING_WATER, 0));
                    }
                    2 => {
                        let _ = neighborhood.set_state(world_x, 61, world_z, state(STILL_WATER, 1));
                    }
                    _ => {}
                }
                if (x * 17 + z) % 5 == 0 {
                    let _ = neighborhood.set_state(world_x, 62, world_z, state(TORCH, 0));
                }
            }
        }

        let _ = neighborhood.set_state(origin_x, 126, origin_z, state(STILL_WATER, 0));
        let _ = neighborhood.set_state(origin_x, 127, origin_z, state(STONE, 0));
        let _ = neighborhood.set_state(origin_x + 1, 0, origin_z, state(STILL_WATER, 0));

        OverworldFreezeFrostPopulator::new().populate(&mut neighborhood);

        assert_eq!(hash_neighborhood(&neighborhood), 0xa142_b37d_e832_30d5);
        assert_eq!(block_count(&neighborhood, ICE), 128);
        assert_eq!(block_count(&neighborhood, STILL_WATER), 66);
        assert_eq!(block_count(&neighborhood, FLOWING_WATER), 0);
        assert_eq!(block_count(&neighborhood, TORCH), 52);
        assert_eq!(
            neighborhood.state(origin_x, 126, origin_z),
            Some(state(ICE, 0)),
        );
        assert_eq!(
            neighborhood.state(origin_x + 1, 0, origin_z),
            Some(state(STILL_WATER, 0)),
        );
    }

    #[test]
    fn independent_warm_biome_fixture_matches() {
        let center = ChunkCoord::new(7, -9);
        let mut neighborhood = PopulationNeighborhood::filled(center, state(AIR, 0), 1);
        let origin_x = 7 * 16;
        let origin_z = -9 * 16;

        for x in 0..16_i32 {
            for z in 0..16_i32 {
                let _ =
                    neighborhood.set_state(origin_x + x, 63, origin_z + z, state(STILL_WATER, 0));
            }
        }

        OverworldFreezeFrostPopulator::new().populate(&mut neighborhood);

        assert_eq!(hash_neighborhood(&neighborhood), 0x88e7_cec4_c9a0_2325);
        assert_eq!(block_count(&neighborhood, ICE), 0);
        assert_eq!(block_count(&neighborhood, STILL_WATER), 256);
    }

    #[test]
    fn fixed_target_cold_biome_set_is_exact() {
        for id in [10_u8, 11, 12, 13, 26, 30, 31, 140, 158] {
            assert!(biome_freezes(id), "id={id}");
        }

        for id in [
            0_u8, 1, 2, 3, 4, 5, 6, 7, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 27, 28, 29,
            32, 33, 34, 35, 36, 37, 38, 39, 129, 130, 131, 132, 133, 134, 149, 151, 155, 156, 157,
            160, 161, 162, 163, 164, 165, 166, 167,
        ] {
            assert!(!biome_freezes(id), "id={id}");
        }
    }

    #[test]
    fn top_rain_generated_material_domain_matches_target() {
        for id in [
            0_u16, 30, 50, 55, 59, 65, 66, 69, 93, 106, 119, 131, 132, 140, 141, 142, 143, 244,
        ] {
            assert!(!material_blocks_motion_or_is_liquid(id), "id={id}");
        }

        for id in [
            1_u16, 2, 3, 4, 5, 8, 9, 10, 11, 17, 23, 24, 29, 43, 44, 46, 47, 48, 52, 54, 58, 60,
            61, 64, 67, 70, 71, 78, 79, 80, 85, 97, 98, 101, 102, 109, 120, 128, 134, 159, 162,
            163, 172, 179, 193, 196, 198, 243,
        ] {
            assert!(material_blocks_motion_or_is_liquid(id), "id={id}");
        }
    }
}
