[package]
name = "cobblestone-client-bootstrap"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
cobblestone-target.workspace = true
bytes.workspace = true
cobblestone-protocol84 = { path = "../../../native/protocol84" }
cobblestone-runtime = { path = "../../../native/runtime" }
cobblestone-transport = { path = "../../../native/transport" }
raknet-rust.workspace = true
tokio.workspace = true

[lints]
workspace = true
