[package]
name = "cobblestone-protocol84"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
bitflags.workspace = true
cobblestone-core = { path = "../core" }
flate2.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
